apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificatie
metadata:
    name: <domain>-tls
spec:
    secretName: <domain-name>
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: <domain-name>
    dnsNames:
        - <domain-name>
        - <domain-name with www>
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - <domain-name>
                - <domain-name with www>